import { cta, feature, hero, link, seo, step } from './helpers';

/** Copied from the previous hardcoded app/landlords, app/lettings-agents and app/property-managers pages (service links now go straight to /services/...) */
export default [
  {
    _id: 'audience-landlords',
    _type: 'audiencePage',
    title: "Landlords",
    path: '/landlords',
    hero: hero("Services for Landlords", "Landlords need accurate, unbiased reporting to protect their investment. miServices provides inventory reports, inspections, and check-outs tailored for individual or portfolio landlords."),
    intro: { heading: "Services for Landlords", text: "Whether you're a landlord with a single property or a portfolio, our professional inspection services give you peace of mind and protect your investment. We provide independent, impartial reporting that stands up to scrutiny and protects all parties.", points: ["Inventory reporting", "Check-ins & check-outs", "Regular property visits", "Maintenance observations", "Deposit dispute protection", "Independent, unbiased reports"] },
    servicesHeading: "Our Services",
    services: [
      feature(undefined, "Inventory Reports", "Detailed documentation of your property's condition and contents", "/services/inventory-reports"),
      feature(undefined, "Check-In Services", "Professional tenant move-in inspections", "/services/check-ins"),
      feature(undefined, "Check-Out Inspections", "Comprehensive end-of-tenancy inspections", "/services/check-outs"),
      feature(undefined, "Property Visits", "Regular checks to ensure property standards are maintained", "/services/property-visits"),
      feature(undefined, "Block Management", "Inspections for multi-unit property owners", "/services/block-management"),
    ],
    benefitsHeading: "Why Landlords Choose Us",
    benefits: [
      feature("home", "Property Protection", "Comprehensive documentation safeguards your investment"),
      feature("shield", "Independent Reports", "Impartial, professional inspections you can trust"),
      feature("pound", "Deposit Protection", "Clear evidence for fair deposit resolutions"),
      feature("fileText", "Professional Documentation", "Legally compliant reports that stand up in disputes"),
    ],
    processHeading: "How It Works",
    processSteps: [
      step("Book Online", "Choose your service and select a convenient date"),
      step("Professional Inspection", "Our trained operative visits your property"),
      step("Quality Check", "Report is produced and quality checked"),
      step("Report Delivered", "Digital report delivered within 24-48 hours"),
    ],
    cta: cta("Protect Your Investment Today", "Professional property inspections to safeguard your rental property", link("Book a Service", "/booking"), link("Find Your Local Operative", "/our-network")),
    seo: seo("Services for Landlords | Inventory & Inspections", "Professional inventory reports, inspections & check-outs for landlords. Protect your deposit and investment with impartial third-party documentation.", "landlord property inspections, inventory reports for landlords, deposit protection, property checks"),
  },
  {
    _id: 'audience-lettings-agents',
    _type: 'audiencePage',
    title: "Lettings Agents",
    path: '/lettings-agents',
    hero: hero("Services for Lettings Agents", "miServices supports letting agents with fast, consistent, and compliant property reports — from inventory to check-out. Designed to streamline your workflow and improve reporting accuracy across your portfolio."),
    intro: { heading: "How We Help Lettings Agents", text: "Running a busy lettings agency means balancing client expectations, compliance requirements, and operational efficiency. miServices takes the burden of property inspections off your hands, allowing you to focus on what you do best — growing your business and serving your clients.", points: ["Outsourced inventory & inspection services", "Mid-tenancy visits", "End-of-tenancy check-outs", "Digital reporting", "Fast turnaround", "Nationwide coverage"] },
    servicesHeading: "Our Services",
    services: [
      feature(undefined, "Inventory Reports", "Comprehensive property documentation at the start of tenancies", "/services/inventory-reports"),
      feature(undefined, "Check-In Services", "Professional tenant move-in services with detailed reporting", "/services/check-ins"),
      feature(undefined, "Check-Out Inspections", "End of tenancy inspections for deposit negotiations", "/services/check-outs"),
      feature(undefined, "Property Visits", "Regular mid-tenancy inspections to maintain property standards", "/services/property-visits"),
      feature(undefined, "Block Management", "Comprehensive inspections for multi-unit properties", "/services/block-management"),
    ],
    benefitsHeading: "Why Letting Agents Choose Us",
    benefits: [
      feature("users", "Nationwide Coverage", "Consistent service across all your properties, wherever they are"),
      feature("shield", "Professional Clerks", "Trained, experienced operatives delivering quality reports"),
      feature("fileText", "Consistent Formatting", "Standardized reports that meet industry compliance standards"),
      feature("clock", "Reduced Admin Workload", "Free up your team to focus on core business activities"),
    ],
    cta: cta("Ready to Streamline Your Operations?", "Join hundreds of lettings agents who trust miServices for their property inspections", link("Book a Service", "/booking"), link("Find Your Local Operative", "/our-network")),
    seo: seo("Services for Letting Agents | Outsourced Property Reporting", "Professional inventory, check-in, check-out & inspection solutions for letting agents. Nationwide coverage, fast turnaround, consistent reporting standards.", "letting agents inventory service, property reports for agents, outsourced inspections, lettings compliance"),
  },
  {
    _id: 'audience-property-managers',
    _type: 'audiencePage',
    title: "Property Managers",
    path: '/property-managers',
    hero: hero("Services for Property Managers", "Property managers rely on miServices for portfolio-wide reporting, scheduled inspections, block management checks, and accurate compliance documentation."),
    intro: { heading: "What We Offer", text: "Managing multiple properties requires reliable, consistent inspection services. Our nationwide network ensures you receive the same high-quality service across all your properties, regardless of location. We understand the unique challenges of portfolio management and provide tailored solutions to meet your needs.", points: ["Block management inspections", "Mid-tenancy visits", "Portfolio-wide scheduling", "Custom reporting formats", "Compliance checks", "Dedicated account management"] },
    servicesHeading: "Our Services",
    services: [
      feature(undefined, "Inventory Reports", "Comprehensive property documentation for your entire portfolio", "/services/inventory-reports"),
      feature(undefined, "Check-In Services", "Professional move-in inspections with standardized reporting", "/services/check-ins"),
      feature(undefined, "Check-Out Inspections", "Evidence-based end-of-tenancy reports for deposit management", "/services/check-outs"),
      feature(undefined, "Property Visits", "Scheduled mid-tenancy inspections to maintain standards", "/services/property-visits"),
      feature(undefined, "Block Management", "Specialist inspections for multi-unit properties and developments", "/services/block-management"),
    ],
    benefitsHeading: "Why Property Managers Choose Us",
    benefits: [
      feature("users", "Portfolio-Wide Consistency", "Same quality standards across all your properties"),
      feature("shield", "Compliance Assured", "Reports that meet all regulatory requirements"),
      feature("fileText", "Custom Reporting", "Tailored formats to match your management systems"),
      feature("clock", "Flexible Scheduling", "Coordinate inspections across multiple properties easily"),
    ],
    cta: cta("Let's Discuss Your Portfolio", "We offer customized solutions for property management companies of all sizes", link("Book a Service", "/booking"), link("Find Your Local Operative", "/our-network")),
    seo: seo("Services for Property Managers | Portfolio Reporting", "Professional reporting, compliance checks & block management services for property managers. Nationwide coverage with consistent standards.", "property management inspections, portfolio reporting, block management, compliance checks"),
  },
];
